### ISSUE TITLE
TinyCore 11.x released

### ISSUE THREAD

**Issue by aw** [tatsushid/docker-tinycore#11]
Hi @tatsushid, I was wondering if you have plans to publish a release for `TinyCore 11.x`. I can make a pull request with the changes if you're too busy.

Thanks.

**Comment by tatsushid** [comment]
Thanks for notifying it! I missed that info. I'm going to check it in this weekend

**Comment by aw** [comment]
Great, thank you!

**Comment by aw** [comment]
Updating this issue: I tested the TC11 image and it works perfectly. Thanks!
